server:
  port: 8081

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
# if we do not specify application name below it would be global for all the feign clients.
account:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 3000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0


hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 60000 # default, after how many miliseconds circuit has to be opened
        errorThresholdPercentage: 50
        requestVolumeThreshold: 60
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# since turbine by default looks for /actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health

spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      host: localhost
      port: 8500

